# Generated by Django 6.1.1 on 2026-10-03 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sec_audit_log',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
