# Generated by Django 6.1.1 on 2026-10-05 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guard', '0002_sec_audit_log_ip_address'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sec_audit_log',
            options={'verbose_name': 'Security Audit Log', 'verbose_name_plural': 'Security Audit Logs'},
        ),
        migrations.AlterModelOptions(
            name='user_input',
            options={'verbose_name': 'User Input', 'verbose_name_plural': 'User Inputs'},
        ),
        migrations.AlterField(
            model_name='sec_audit_log',
            name='flagged_keywords',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterModelTable(
            name='sec_audit_log',
            table='cyberguard_security_log',
        ),
        migrations.AlterModelTable(
            name='user_input',
            table='cyberguard_user_input',
        ),
    ]
